-- 创建表结构

-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    nickname VARCHAR(50),
    age INTEGER,
    gender VARCHAR(10),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

-- 设备表
CREATE TABLE IF NOT EXISTS device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    device_type VARCHAR(50) NOT NULL,
    location VARCHAR(100),
    status VARCHAR(20),
    control_params TEXT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

-- 环境数据表
CREATE TABLE IF NOT EXISTS environment_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    temperature DOUBLE NOT NULL,
    humidity DOUBLE NOT NULL,
    co2 DOUBLE,
    ammonia DOUBLE,
    light_intensity DOUBLE,
    create_time TIMESTAMP
);

-- 预警表
CREATE TABLE IF NOT EXISTS alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    level VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(20),
    device_id VARCHAR(50) NOT NULL,
    create_time TIMESTAMP
);

-- 视频监控表
CREATE TABLE IF NOT EXISTS video_monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    device_id VARCHAR(50) NOT NULL,
    rtsp_url VARCHAR(255),
    status VARCHAR(20),
    location VARCHAR(100),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
